### PR TITLE
Prevent Invalid Charge being processed

### LINKED ISSUE #20: 3DS Challenge Timeout Incorrectly Processes Order as Successful
When a 3DS challenge times out during the payment process, the order request is incorrectly marked as successful. 

Steps to Reproduce:

1. Initiate a payment that requires 3DS authentication.
2. Allow the 3DS challenge to time out without completing it.
3. Observe that the order is processed as successful instead of failing.

### PR DESCRIPTION
**Pull request by wrunivapay**
Closes #20

### CODE REVIEW

**Comment by wrunivapay** [comment]
🤦 i forgot which store did i use on E2E...

File: UnivaPay-for-WooCommerce/tests/e2e/models/wp/site/classic-checkout.ts [hunk 1]
```diff
@@ -48,7 +48,7 @@ class WCClassicCheckoutPage {
 
     async finishCheckout(t: TestController) {
         await t
-            .click(this.placeOrderButton)
+            .click(this.placeOrderButton).wait(10000)
     }
```
Comment (msbomrel) [inline UnivaPay-for-WooCommerce/tests/e2e/models/wp/site/classic-checkout.ts:52]: @wrunivapay Other codes looks fine to me, why wait for 10 secs? Is there any way we can wait only for the time when next event occurs...

Comment (wrunivapay) [reply UnivaPay-for-WooCommerce/tests/e2e/models/wp/site/classic-checkout.ts:52]: @msbomrel 🤔 While we could wait indefinitely, we want to enforce a time limit here. If the page doesn't produce the expected result within that time, we want the process to fail. To be honest, I haven't found a better approach to handle this yet.
